#!/usr/bin/env php
<?php
require __DIR__.'/bootstrap.php';
use Rentman\Rentman;

echo "REFRESHING\n";
$publicDir = __DIR__.'/public';

if (!file_exists($publicDir)) {
    die("NO PUBLIC DIRECTORY AVAILABLE");
}

//have we got an xml file to parse
$xmlfile = "";
foreach (scandir($publicDir) as $file) {
    $ext = pathinfo($file, PATHINFO_EXTENSION);
    if ($ext == 'xml') {
        $xmlfile = $publicDir.'/'.$file;
    }
}
if ($xmlfile != '' && file_exists($xmlfile)) {
    try {
        $jsonFile = $publicDir.'/properties.json';
        fopen($jsonFile, 'w+');
        $rentman = new Rentman($xmlfile);
        $transformed = $rentman->buildTransformedDataArray();
        //header('Content-Type: application/json');
        file_put_contents($jsonFile, json_encode($transformed['properties']));
        echo "REFRESHED SUCCESSFULLY";
    } catch (\Exception $e) {
        die($e->getMessage);
    }
} else {
    die("No XML file found");
}
